#!/usr/bin/env node

/*
This program prompts a user to travel through an invisible maze.
By entering a direction (N,S,W,E) the user will find out if it is correct - 
if it is, the user will progress to the next step.
If not, the user stays on the current step and is prompted to try again.
*/

var correctMaze = ['n','e'];
var maze = require('commander');
var prompt = require('prompt');

prompt.start();
console.log("You are in an invisible maze. Enter a direction (N,S,W,E) - ");
console.log("try not to hit an invisible wall.");
takeThisStep(0);

function takeThisStep(index) {
	prompt.get(['direction'], function(err,result){
		var direction = result.direction;
		response(index,direction);
	});
}

function takeNextStep(index){
	prompt.get(['direction'], function(err,result){
		var direction = result.direction;
		response(index,direction);
	});
}

function mazeEscape() {
	console.log("You won!! Thanks for playing!");
}

function response(index,direction) {
	direction = direction.toLowerCase();
	if(direction === correctMaze[index]){
		if(index === correctMaze.length - 1) {
			mazeEscape();
		} else {
			console.log("Great progress so far! Which direction next?");
			takeNextStep(index + 1);
		}			
	} else {
		console.log("Sorry, that was the wrong direction, try again.");
		takeThisStep(index);
	}	
}

